---
title: "Breakdown of the Ontario Sunshine List"
author: "Ricardo Chejfec"
date: "25/03/2021"
output: 
    md_document:
    variant: markdown_github
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r libs, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)                            # Lib for plotting
library("gridExtra")
library(hrbrthemes)
library(ggthemes)
library(ggpubr)
library(kableExtra)
library(remotes)
library(waffle)


cbp1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

theme_ric <- function(plt, plot.case) {
  x <- plt + theme(
    legend.text = element_text(size=18),
    axis.text=element_text(size=16),
    axis.title=element_text(size=14),
    title = element_text(size=18)
  )
  if (plot.case == "bar") {
    x = x + scale_fill_brewer(cbp1) + scale_color_brewer(cbp1)
  } else {
    x = x + scale_color_brewer(palette="RdGy")
  }
  return(x)
}

```

## The Ontario Sunshine List 

<!-- What is it?  -->



<!-- Break-Down - General -->

```{r set_up, echo=FALSE, message=FALSE, warning=FALSE}

master <- data.table::fread(file = "data/master.csv")
master <- as_tibble(master)
master = mutate(master, calendar_year = calendar_year-1996)

master = master %>% 
  mutate(salary_paid = 
           ifelse(salary_paid>3000000,
                  salary_paid/100,
                  salary_paid),
         total_income = salary_paid + taxable_benefits) %>% 
  rename(salary = salary_paid,
         benefits = taxable_benefits,
         year = calendar_year)

master = master %>% 
    mutate(sector = case_when(
        str_detect(sector, "government ") ~ "ontario public service",
        str_detect(sector, "hydro one") ~ "ontario power generation",
        TRUE ~ sector
        ),
        sector = str_to_title(sector)
    ) %>% 
  filter(sector!="Seconded")

# dta <- master %>%
#     group_by(sector) %>%
#     count() %>% 
#     ungroup() %>% 
#     mutate(i=row_number())
# 
# dta2 <- master %>%
#     group_by(job_title) %>%
#     count() %>%
#     ungroup() %>%
#     mutate(i=row_number())

#ggplot(master, aes(x=calendar_year, y=total_income, color=factor(sector))) + geom_point(alpha=.1)

```

### 2020 in Summary 


```{r sum20, echo=FALSE, fig.height=10, fig.width=14, message=FALSE, warning=FALSE}
# 2020 
master_20 = filter(master, year == 24)
master_19 = filter(master, year == 23)

# Sector Summary 20 
secsum_20 = master_20 %>% 
  group_by(sector) %>% 
    summarise(money = mean(total_income),
                                 sec_feq=n()) 

secsum_20 = arrange(secsum_20, 
                    desc(sec_feq)) %>%
    mutate(rank = 1:nrow(secsum_20))

waf <- ggplot(
  secsum_20[order(secsum_20$sec_feq),],
  aes(fill = reorder(sector, rank),
      values = round(sec_feq/100))
  ) +
  expand_limits(x=c(0,0),
                y=c(0,0)) +
  coord_equal() +
  labs(fill = NULL,
       colour = NULL) +
  # theme_ipsum_rc(grid="") +
  theme_enhance_waffle() 

waf + geom_waffle(
    n_rows = 10, 
    size = .5, 
    colour = "black", 
    make_proportional = TRUE,
    flip= TRUE,
    radius = unit(4, "pt")) +
  theme_bw() +
  theme_enhance_waffle() +
  theme(legend.position = "bottom",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.ticks = element_blank(),
    legend.text = element_text(size=18),
    legend.title = element_blank(),
    legend.margin=margin(-20,0,40,0),
    legend.box.margin=margin(-10,-10,-10,-10)) +
  scale_fill_brewer(palette="RdGy") +
  guides(fill = guide_legend(nrow = 3))


p_secsum_d_20 <- ggplot(secsum_20, 
       aes(y=reorder(factor(sector),
                     money), 
           x=money, 
           fill=reorder(factor(sector),
                        rank))) + 
  geom_bar(stat="identity", color="black") +
  ggtitle("Average Earnings by Sector in 2020") +
  xlab("Avg Earnings")+
  ylab(element_blank())+
  scale_x_continuous(labels=scales::dollar_format()) +
  theme_bw() +
  theme(legend.position = "none") 

theme_ric(p_secsum_d_20, "bar")

# grid.arrange(p_secsum_20, p_secsum_d_20, ncol=2)


```

### Change from 2019 to 2020

```{r delta20, echo=FALSE, fig.height=7, fig.width=14, message=FALSE, warning=FALSE, , echo=FALSE}
# Sector change from last year 

#Get 19
secsum_19 = master_19 %>% 
  group_by(sector) %>% 
  summarise(money19 = mean(total_income),
            n19=n())

secsum_19 = arrange(secsum_19, desc(n19)) %>% mutate(rank = 1:nrow(secsum_19))

change_1920 = left_join(secsum_20, secsum_19,"sector") %>% 
  mutate(delta_count = sec_feq - n19, 
         delta_money = money - money19)

p_change_1920 <- ggplot(change_1920, 
                        aes(x=reorder(sector,
                                      -delta_count), 
                            y=delta_count, 
                            label=delta_count, 
                            color=reorder(sector,
                                          rank.x))) +
  geom_point(aes(fill=reorder(sector,
                              rank.x)),
             stat="identity",
             size=8,
             colour="black",
             pch=21) + 
  geom_segment(aes(y=0,
                   x=sector,
                   yend=delta_count,
                   xend=sector,
                   color=reorder(sector,
                              rank.x)))+
  geom_text(color="black",
            size=5,
            nudge_x = .25) + 
  scale_y_continuous(labels=scales::number_format(),
                     limits = c(-500,17500)) +
  coord_flip() + 
  ggtitle("Change from 2019 - 2020 by Sector")+
  ylab("Delta Count")+
  xlab("")+
  theme_bw()+
  theme(legend.position = "none")

p_change_1920_d <- ggplot(change_1920,
                          aes(x=reorder(sector,
                                        -delta_money), 
                              y=delta_money, 
                              label=round(delta_money), 
                              color=reorder(sector,
                              rank.x)))+
  geom_point(aes(fill=reorder(sector,
                              rank.x)),
             stat="identity", 
             size=8,
             colour="black",
             pch=21) + 
  geom_segment(aes(y=0,
                   x=sector,
                   yend=delta_money,
                   xend=sector,
                   color=reorder(sector,
                              rank.x)))+
  geom_text(color="black",
            size=5,
            nudge_x=.25) + 
  coord_flip() + 
  ggtitle("Change in Avg Earnings from 2019 - 2020 by Sector")+
  ylab("Delta Avg Earnings")+
  xlab("")+ 
  theme_bw()+
  scale_y_continuous(labels=scales::dollar_format(),
                     limits = c(-7500,7500)) +
  theme(legend.position = "none")

theme_ric(p_change_1920, "bar")
theme_ric(p_change_1920_d, "bar")

```

### What About Job Titles 

```{r jobtitles, echo=FALSE, fig.height=7, fig.width=14, message=FALSE, warning=FALSE, , echo=FALSE}

jobs20 = master_20 %>% 
  group_by(sector) %>% 
  count(job_title, sort=TRUE) %>% 
  ungroup() %>% 
  group_by(sector) %>% 
  slice(1:5)

crown_20 = jobs20 %>% 
  filter(sector == "Crown Agencies")
  
univ_20 = jobs20 %>% 
  filter(sector == "Universities")

power_20 = jobs20 %>% 
  filter(sector == "Ontario Power Generation")
  
jobs19 = master_19 %>% 
  group_by(sector) %>% 
  count(job_title, sort=TRUE) %>% 
  ungroup() %>% 
  group_by(sector) %>% 
  slice(1:5)

crown_19 = jobs19 %>% 
  filter(sector == "Crown Agencies")
  
univ_19 = jobs19 %>% 
  filter(sector == "Universities")

power_19 = jobs19 %>% 
  filter(sector == "Ontario Power Generation")
  
grid.arrange(
  tableGrob(crown_20),
  tableGrob(crown_19),
  nrow=1)

grid.arrange(
  tableGrob(univ_20),
  tableGrob(univ_19),
  nrow=1)

grid.arrange(
  tableGrob(power_20),
  tableGrob(power_19),
  nrow=1)
```

### Summary Across Time  

```{r timesum, echo=FALSE, fig.height=14, fig.width=14, message=FALSE, warning=FALSE}
# Long Summary 
p_longsum <- ggplot(master, 
       aes(x=year)) +
  scale_y_continuous(labels=scales::number_format())+
  geom_bar() +
  ggtitle("Count Across Time")+
  ylab("Count")+
  xlab("Year")
  theme_bw() 

p_longsum_d <- ggplot(master, 
       aes(y=total_income, x=year)) + 
  geom_bar(stat="summary") +
  scale_y_continuous(labels=scales::dollar_format()) +
  ggtitle("Avg Earnings Across Time")+
  ylab("Avg Earnings")+
  xlab("Year")
  theme_bw()

grid.arrange(theme_ric(p_longsum, "bar"), theme_ric(p_longsum_d,"bar"), nrow=2)
```

### Sector Summary Across Time

```{r sectimesum, echo=FALSE, fig.height=14, fig.width=14, message=FALSE, warning=FALSE, , echo=FALSE}
# Long Sector Summary 

longsecsum_d = master %>% 
  group_by(sector, year) %>% 
  summarise(avg_income = mean(total_income))

p_longsecsum <- ggplot(master,aes(x=year)) +
    geom_histogram(aes(fill=factor(sector)),
                   binwidth=.5) + 
    scale_y_continuous(labels=scales::number_format()) +
    ggtitle("Sector Breakdown Through Time")+
    xlab("Year")+
    ylab("Count")+
    theme_bw() +
    theme(legend.title = element_blank(),
          legend.position = "bottom")

p_longsecsum_d <- ggplot(longsecsum_d, 
                         aes(x=year,
                             y=avg_income)) + 
    geom_line(aes(color=factor(sector))) + 
    scale_y_continuous(labels=scales::dollar_format(),
                       limits = c(100000, 175000)) +
    ggtitle("Sector Avg Earnings Through Time")+
    xlab("Avg Earnings")+
    ylab("Count")+
    theme_bw() + 
    theme(legend.position = "none") 

grid.arrange(theme_ric(p_longsecsum, "bar"), theme_ric(p_longsecsum_d, "bar"), nrow=2)

```

## What About Inflation

```{r infl_setup, echo=FALSE, fig.height=8, fig.width=14, message=FALSE, warning=FALSE, , echo=FALSE}
inflation <- readr::read_csv("data/inflation.csv")
inflation = head(inflation, 1)
inflation = pivot_longer(inflation, 2:26, names_to = "year",
                         values_to = "cpi") %>%
    mutate(year = as.numeric(year)-1996,
           indexed = cpi/88.2) %>%
    select(year, indexed)

master_inf = left_join(x=master, y=inflation) %>%
    mutate(income_inf = total_income / indexed,
           salary_inf = salary / indexed,
           benefits_inf = benefits / indexed)

violins <- ggplot(master_inf, aes(x=factor(year), y=income_inf)) +
  geom_violin() + 
  geom_hline(yintercept = 100000, color="red") + 
  scale_y_continuous(labels=scales::dollar_format(),
                     limits = c(50000,500000)) +
  theme_bw()

theme_ric(violins, "bar")

```

### 2020 Adjusted

```{r infl_2020, echo=FALSE, fig.height=8, fig.width=14, message=FALSE, warning=FALSE, , echo=FALSE}
master_adj = master_inf %>% filter(salary_inf>=100000)

master_20_adj = master_adj %>% filter(year==24)

secsum_20_adj = master_20_adj %>% 
  group_by(sector) %>% summarise(money = mean(income_inf), sec_feq=n()) 

secsum_20_adj = secsum_20_adj %>% mutate(perc = sec_feq/nrow(master_20))

p_secsum_20_adj <- ggplot(secsum_20_adj, 
       aes(y=reorder(factor(sector), sec_feq), x=sec_feq, fill=sector)) + 
  geom_bar(stat="identity") +
  scale_x_continuous(labels=scales::number_format()) +
  theme_bw() +
  theme(legend.position = "none",
        axis.text=element_text(size=14))+
  scale_fill_brewer(palette="RdGy")

p_secsum_d_20_adj <- ggplot(secsum_20_adj, 
       aes(y=reorder(factor(sector), money), x=money, fill=sector)) + 
  geom_bar(stat="identity") +
  scale_x_continuous(labels=scales::dollar_format()) +
  theme_bw()+
  theme(axis.text=element_text(size=14),
        legend.text = element_text(size=14),
        legend.title = element_blank(),
        legend.position = "none") +
  scale_fill_brewer(palette="RdGy")


# grid.arrange(p_secsum_20 + scale_fill_brewer(palette="RdGy"), 
#              p_secsum_20_adj,
#              ncol=2)
grid.arrange(p_secsum_d_20 + scale_fill_brewer(palette="RdGy"),
             p_secsum_d_20_adj, ncol=2)

```

### Managers versus Professionals

```{r testing_jobs, echo=FALSE, fig.height=10, fig.width=14, message=FALSE, warning=FALSE}
test_jobs_20 <- master_20 %>%
    group_by(job_title) %>%
    count() %>%
    ungroup() %>%
    mutate(i=row_number())

prac_jobs_20 <- master_20 %>% 
    mutate(job_title = case_when(
        grepl(pattern = "chief", x = job_title) ~ "Mgmt",
        grepl(pattern = "manager", x = job_title) ~ "Mgmt",
        grepl(pattern = "director", x = job_title) ~ "Mgmt",
        grepl(pattern = "principal", x = job_title) ~ "Mgmt",
        grepl(pattern = "sergeant", x = job_title) ~ "Mgmt",
        grepl(pattern = "captain", x = job_title) ~ "Mgmt",
        grepl(pattern = "leader", x = job_title) ~ "Mgmt",
        grepl(pattern = "lead", x = job_title) ~ "Mgmt",
        grepl(pattern = "chair", x = job_title) ~ "Mgmt",
        grepl(pattern = "supervisor", x = job_title) ~ "Mgmt",
        grepl(pattern = "head", x = job_title) ~ "Mgmt",
        grepl(pattern = "direction", x = job_title) ~ "Mgmt",
        grepl(pattern = "superintendent", x = job_title) ~ "Mgmt",
        grepl(pattern = "coordinator", x = job_title) ~ "Mgmt",
        grepl(pattern = "president", x = job_title) ~ "Mgmt",
        grepl(pattern = "gestionnaire", x = job_title) ~ "Mgmt",
        grepl(pattern = "dean", x = job_title) ~ "Mgmt",
        grepl(pattern = "commander", x = job_title) ~ "Mgmt",
        grepl(pattern = "lieutenant", x = job_title) ~ "Mgmt",
        grepl(pattern = "administrator", x = job_title) ~ "Mgmt",
        grepl(pattern = "vicedoyen", x = job_title) ~ "Mgmt",
        grepl(pattern = "minister", x = job_title) ~ "Mgmt",
        grepl(pattern = "executive officer", x = job_title) ~ "Mgmt",
        grepl(pattern = "deputy", x = job_title) ~ "Mgmt",
        grepl(pattern = "directeur", x = job_title) ~ "Mgmt",
        grepl(pattern = "committee", x = job_title) ~ "Mgmt",
        grepl(pattern = "commissioner", x = job_title) ~ "Mgmt",
        grepl(pattern = "coordonnateur", x = job_title) ~ "Mgmt",
        TRUE ~ "Proff"
        ))

bop_jobs_20 <- prac_jobs_20 %>%
    group_by(job_title) %>%
    count() %>%
    ungroup() %>%
    mutate(i=row_number())

test_jobs_20_adj <- master_20_adj %>%
    group_by(job_title) %>%
    count() %>%
    ungroup() %>%
    mutate(i=row_number())

prac_jobs_20_adj <- master_20_adj %>% 
    mutate(job_title = case_when(
        grepl(pattern = "chief", x = job_title) ~ "Mgmt",
        grepl(pattern = "manager", x = job_title) ~ "Mgmt",
        grepl(pattern = "director", x = job_title) ~ "Mgmt",
        grepl(pattern = "principal", x = job_title) ~ "Mgmt",
        grepl(pattern = "sergeant", x = job_title) ~ "Mgmt",
        grepl(pattern = "captain", x = job_title) ~ "Mgmt",
        grepl(pattern = "leader", x = job_title) ~ "Mgmt",
        grepl(pattern = "lead", x = job_title) ~ "Mgmt",
        grepl(pattern = "chair", x = job_title) ~ "Mgmt",
        grepl(pattern = "supervisor", x = job_title) ~ "Mgmt",
        grepl(pattern = "head", x = job_title) ~ "Mgmt",
        grepl(pattern = "direction", x = job_title) ~ "Mgmt",
        grepl(pattern = "superintendent", x = job_title) ~ "Mgmt",
        grepl(pattern = "coordinator", x = job_title) ~ "Mgmt",
        grepl(pattern = "president", x = job_title) ~ "Mgmt",
        grepl(pattern = "gestionnaire", x = job_title) ~ "Mgmt",
        grepl(pattern = "dean", x = job_title) ~ "Mgmt",
        grepl(pattern = "commander", x = job_title) ~ "Mgmt",
        grepl(pattern = "lieutenant", x = job_title) ~ "Mgmt",
        grepl(pattern = "administrator", x = job_title) ~ "Mgmt",
        grepl(pattern = "vicedoyen", x = job_title) ~ "Mgmt",
        grepl(pattern = "minister", x = job_title) ~ "Mgmt",
        grepl(pattern = "executive officer", x = job_title) ~ "Mgmt",
        grepl(pattern = "deputy", x = job_title) ~ "Mgmt",
        grepl(pattern = "directeur", x = job_title) ~ "Mgmt",
        grepl(pattern = "committee", x = job_title) ~ "Mgmt",
        grepl(pattern = "commissioner", x = job_title) ~ "Mgmt",
        grepl(pattern = "coordonnateur", x = job_title) ~ "Mgmt",
        grepl(pattern = "mayor", x = job_title) ~ "Mgmt",
        grepl(pattern = "surintendante", x = job_title) ~ "Mgmt",
        grepl(pattern = "vicerecteur", x = job_title) ~ "Mgmt",
        grepl(pattern = "vicepésident", x = job_title) ~ "Mgmt",
        grepl(pattern = "viceprovost", x = job_title) ~ "Mgmt",
        grepl(pattern = "provost", x = job_title) ~ "Mgmt",
        grepl(pattern = "surintendance", x = job_title) ~ "Mgmt",
        grepl(pattern = "coordonnateur", x = job_title) ~ "Mgmt",
        TRUE ~ "Proff"
        ))

test_1 <- prac_jobs_20_adj %>%
    group_by(job_title) %>%
    count() %>%
    ungroup() %>%
    mutate(i=row_number())

alljobs20 = ggplot(bop_jobs_20, aes(x = job_title,y=n)) + geom_bar(stat = "summary")
alljobs20_adj = ggplot(test_1, aes(x = job_title,y=n)) + geom_bar(stat = "summary")
grid.arrange(alljobs20,alljobs20_adj, ncol=2)


```


### Change from 2019 to 2020 - Adjusted

```{r infl_delta_20, echo=FALSE, fig.height=8, fig.width=14, message=FALSE, warning=FALSE, , echo=FALSE}

master_19_adj = master_adj %>% filter(year==23)

secsum_19_adj = master_19_adj %>% 
  group_by(sector) %>% summarise(money19 = mean(income_inf), n19=n())

change_1920_adj = left_join(secsum_20_adj, secsum_19_adj) %>% 
  mutate(delta_count = sec_feq - n19, 
         delta_money = money - money19)

p_change_1920_adj <- ggplot(change_1920_adj, aes(x=reorder(sector, -delta_count), y=delta_count, label=delta_count, color=sector))+
  geom_point(stat="identity", size=8) + 
  geom_segment(aes(y=0,
                   x=sector,
                   yend=delta_count,
                   xend=sector,
                   color=sector))+
  geom_text(color="black", size=5) + 
  scale_y_continuous(labels=scales::number_format(),
                     limits = c(-50,600)) +
  coord_flip() + 
  theme_bw()+
  theme(legend.position = "none", axis.text=element_text(size=14))

p_change_1920_d_adj <- ggplot(change_1920_adj, aes(x=reorder(sector, -delta_money), y=delta_money, label=delta_money, color=sector))+
  geom_point(stat="identity", size=8) + 
  geom_segment(aes(y=0,
                   x=sector,
                   yend=delta_money,
                   xend=sector,
                   color=sector))+
  geom_text(color="black", size=5) + 
  coord_flip() + 
  theme_bw()+
  scale_y_continuous(labels=scales::dollar_format(), limits = c(-5000,15000)) +
   theme(legend.position = "none", axis.text=element_text(size=14))

p_change_1920_adj + scale_fill_brewer(palette="RdGy")
p_change_1920_d_adj + scale_fill_brewer(palette="RdGy")
```

### Adjusted Job Titles 

```{r inf_jobtitles, echo=FALSE, fig.height=7, fig.width=14, message=FALSE, warning=FALSE, , echo=FALSE}
jobs20_adj = master_20_adj %>% 
  group_by(sector) %>% 
  count(job_title, sort=TRUE) %>% 
  ungroup() %>% 
  group_by(sector) %>% 
  slice(1:5)

jobs19_adj = master_19_adj %>% 
  group_by(sector) %>% 
  count(job_title, sort=TRUE) %>% 
  ungroup() %>% 
  group_by(sector) %>% 
  slice(1:5)
```

### Summary Across Time - Adjusted

```{r inf_timesum, echo=FALSE, fig.height=14, fig.width=14, message=FALSE, warning=FALSE, , echo=FALSE}
# Long Summary 

p_longsum_adj <- ggplot(master_adj, 
       aes(x=year)) + 
  scale_y_continuous(labels=scales::number_format()) +
  geom_bar() +
  theme_bw()

p_longsum_d_adj <- ggplot(master_adj, 
       aes(y=income_inf, x=year)) + 
  geom_bar(stat="summary") +
  scale_y_continuous(labels=scales::dollar_format()) +
  theme_bw() +
  theme(axis.text=element_text(size=14)) 

grid.arrange(p_longsum_adj, p_longsum_d_adj, nrow=2)
```

### Sector Summary Across Time - Adjusted

```{r inf_sectimesum, echo=FALSE, fig.height=14, fig.width=14, message=FALSE, warning=FALSE, , echo=FALSE}
# Long Sector Summary 

longsecsum_d_adj = master_adj %>% 
  group_by(sector, year) %>% 
  summarise(avg_income = mean(income_inf))

p_longsecsum_adj <- ggplot(master_adj,aes(x=year)) +
  geom_histogram(aes(fill=factor(sector)),
                 binwidth=.5) + 
  scale_y_continuous(labels=scales::number_format()) +
  theme_bw() +
  theme(legend.position = "none", axis.text=element_text(size=14))

p_longsecsum_d_adj <- ggplot(longsecsum_d_adj, 
                         aes(x=year, y=avg_income)) + 
  geom_line(aes(color=factor(sector))) + 
  scale_y_continuous(labels=scales::dollar_format(),
                     limits = c(100000, 175000)) +
  theme_bw()+ theme(legend.text = element_text(size=14),
                     legend.title = element_blank(),
                     axis.text=element_text(size=14),
                    legend.position = "top")

grid.arrange(p_longsecsum_adj + scale_fill_brewer(palette="RdGy"),
             p_longsecsum_d_adj + scale_color_brewer(palette="RdGy"),
             nrow=2)

```

```{r tests, echo=FALSE, message=FALSE, warning=FALSE}
# sector adjustment 
# 
# sectors <- master %>% 
#   group_by(calendar_year, sector) %>% 
#   count() %>% 
#   ungroup() %>% 
#   mutate(i=row_number())
# 
# ggplot(sectors, aes(y=sector, x=calendar_year)) + geom_point(alpha=.5)
# 
# sectors2 <- master_sadj %>% 
#   group_by(calendar_year, sector) %>% 
#   count() %>% 
#   ungroup() %>% 
#   mutate(i=row_number())
# 
# ggplot(sectors2, aes(y=sector, x=calendar_year)) + geom_point(alpha=.5)



```



